version: '3.8'

services:
  elemes:
    build: .
    container_name: elemes
    volumes:
      - ../content:/app/content
      - ./static:/app/static
      - ./templates:/app/templates
      - ../tokens_siswa.csv:/app/tokens.csv
    env_file:
      - ../.env
    command: gunicorn --config gunicorn.conf.py app:app
  elemes-ts:
    image: docker.io/tailscale/tailscale:latest
    container_name: elemes-ts
    hostname: ${ELEMES_HOST}
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_SERVE_CONFIG=/config/sinau-c-tail.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
    volumes:
      - ../state:/var/lib/tailscale
      - ./config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    env_file:
      - ../.env

networks:
  main_network:
    drive: bridge
    network_mode: service:elemes-ts
