version: '3.8'

services:
  lms-c:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ../content:/app/content
      - ./static:/app/static
      - ./templates:/app/templates
      - ../tokens_siswa.csv:/app/tokens.csv
    environment:
      - FLASK_ENV=development
    command: python app.py
