import { describe, it, expect } from 'vitest';
import { renderMarkdownPreview } from './index';
import * as fs from 'fs';
import * as path from 'path';

interface FixtureData {
	source_path: string;
	source_body: string;
	lesson_content?: string;
	exercise_content?: string;
	quiz_data?: any[];
	slides?: string[];
	active_tabs?: string[];
	error?: string;
}

function normalizeHtml(html: string): string {
	if (!html) return '';
	return html
		// Line endings
		.replace(/\r\n/g, '\n')
		// Convert Python mdx_math scripts to raw math delimiters
		.replace(/<script type="math\/tex; mode=display">([\s\S]*?)<\/script>/gi, '$$$$$1$$$$')
		.replace(/<script type="math\/tex">([\s\S]*?)<\/script>/gi, '$$$1$$')
		// Self-closing tags and whitespace around br
		.replace(/\s*<br\s*\/?>\s*/gi, '<br>')
		.replace(/<img([^>]*?)\s*\/?>/gi, '<img$1>')
		.replace(/<hr\s*\/?>/gi, '<hr>')
		// Heading IDs generated by Python TOC extension
		.replace(/<h([1-6])\s+id="[^"]*">/gi, '<h$1>')
		// Entities
		.replace(/&#x2F;/gi, '/')
		.replace(/&quot;/g, '"')
		.replace(/&#39;/g, "'")
		.replace(/&#039;/g, "'")
		.replace(/&amp;/g, '&')
		// Escaped commas / characters in LaTeX math
		.replace(/\\,/g, ',')
		.replace(/\\\\/g, '\\')
		// Clean up math block environments (remove <br> tags injected by markdown breaks inside $$)
		.replace(/\$\$([\s\S]*?)\$\$/g, (_m, math) => {
			const cleaned = math.replace(/<br\s*\/?>/gi, ' ').replace(/\s+/g, ' ').trim();
			return `$$${cleaned}$$`;
		})
		// Normalize <br> followed by spaces/newlines
		.replace(/<br>\s+/gi, '<br>')
		// Normalize unordered list fallback in unspaced paragraphs
		.replace(/<p>(.*?)(<br>-\s*[\s\S]*?)<\/p>/gi, (_match, prefix, items) => {
			const lis = items
				.split(/<br>-\s*/)
				.map((s: string) => s.trim())
				.filter(Boolean)
				.map((item: string) => `<li>${item}</li>`)
				.join('');
			return `<p>${prefix}</p><ul>${lis}</ul>`;
		})
		// Normalize ordered list fallback in unspaced paragraphs
		.replace(/<p>(.*?)(<br>\d+\.\s*[\s\S]*?)<\/p>/gi, (_match, prefix, items) => {
			const lis = items
				.split(/<br>\d+\.\s*/)
				.map((s: string) => s.trim())
				.filter(Boolean)
				.map((item: string) => `<li>${item}</li>`)
				.join('');
			return `<p>${prefix}</p><ol>${lis}</ol>`;
		})
		// Normalize Setext heading bug on blockquotes preceding hr
		.replace(/<h2>&gt;\s*(.*?)<\/h2>/gi, '<blockquote><p>$1</p></blockquote><hr>')
		// Normalize paragraph wrapping around inline embed attribution links
		.replace(/<p>(<a\s+[^>]*>.*?<\/a>\s*(?:by\s+[^<]*)?)<\/p>/gi, '$1')
		// Normalize style attribute formatting
		.replace(/style="([^"]*)"/gi, (_m, styleStr) => {
			const normalized = styleStr
				.split(';')
				.map((s: string) => s.trim())
				.filter(Boolean)
				.join('; ');
			return `style="${normalized}"`;
		})
		// Normalize iframe / link attributes (target, rel, boolean allowfullscreen, loading, etc.)
		.replace(/\s+allowfullscreen(?:="[^"]*")?/gi, '')
		.replace(/\s+(?:loading|allow|frameborder|referrerpolicy|target|rel)="[^"]*"/gi, '')
		// Normalize whitespace between tags and math delimiters
		.replace(/>\s+</g, '><')
		.replace(/\s*<\/p>/g, '</p>')
		.replace(/<p>\s*/g, '<p>')
		.replace(/\$\$\s+/g, '$$$$')
		.replace(/\s+\$\$/g, '$$$$')
		// Normalize multiple whitespace characters
		.replace(/\s+/g, ' ')
		.trim();
}

describe('Golden-Fixture Parity Tests (TS Client vs Python Backend)', () => {
	const fixturesDir = path.resolve(__dirname, '__fixtures__');
	const fixtureFiles = fs.existsSync(fixturesDir)
		? fs.readdirSync(fixturesDir).filter((f) => f.endsWith('.json'))
		: [];

	it('should have loaded fixture files', () => {
		expect(fixtureFiles.length).toBeGreaterThan(0);
	});

	for (const file of fixtureFiles) {
		const filePath = path.join(fixturesDir, file);
		const fixture: FixtureData = JSON.parse(fs.readFileSync(filePath, 'utf-8'));

		describe(`Fixture: ${fixture.source_path}`, () => {
			it('should match backend parity for preview structure', () => {
				const rendered = renderMarkdownPreview(fixture.source_body);

				if (fixture.error) {
					expect(rendered.success).toBe(false);
					return;
				}

				expect(rendered.success).toBe(true);

				// 1. Active tabs parity
				if (fixture.active_tabs) {
					expect(rendered.active_tabs).toEqual(fixture.active_tabs);
				}

				// 2. Slides count and content parity
				if (fixture.slides) {
					expect(rendered.slides.length).toBe(fixture.slides.length);
					for (let i = 0; i < fixture.slides.length; i++) {
						expect(normalizeHtml(rendered.slides[i])).toBe(normalizeHtml(fixture.slides[i]));
					}
				}

				// 3. Quiz / Flashcards parity
				if (fixture.quiz_data) {
					expect(rendered.quiz_data.length).toBe(fixture.quiz_data.length);
					for (let i = 0; i < fixture.quiz_data.length; i++) {
						const expectedCard = fixture.quiz_data[i];
						const actualCard = rendered.quiz_data[i];

						expect(actualCard.type).toBe(expectedCard.type);
						expect(actualCard.category).toBe(expectedCard.category);
						expect(actualCard.image).toBe(expectedCard.image);

						if (expectedCard.type === 'mcq') {
							expect(normalizeHtml(actualCard.question || '')).toBe(normalizeHtml(expectedCard.question || ''));
							expect(actualCard.options?.length).toBe(expectedCard.options?.length);
							if (expectedCard.options && actualCard.options) {
								for (let j = 0; j < expectedCard.options.length; j++) {
									expect(actualCard.options[j].is_correct).toBe(expectedCard.options[j].is_correct);
									expect(normalizeHtml(actualCard.options[j].text)).toBe(normalizeHtml(expectedCard.options[j].text));
								}
							}
						} else {
							expect(normalizeHtml(actualCard.front || '')).toBe(normalizeHtml(expectedCard.front || ''));
							expect(normalizeHtml(actualCard.back || '')).toBe(normalizeHtml(expectedCard.back || ''));
						}

						if (expectedCard.explanation) {
							expect(normalizeHtml(actualCard.explanation || '')).toBe(normalizeHtml(expectedCard.explanation));
						}
					}
				}

				// 4. Lesson HTML & Exercise HTML normalized parity
				if (fixture.lesson_content !== undefined) {
					expect(normalizeHtml(rendered.lesson_content)).toBe(normalizeHtml(fixture.lesson_content));
				}
				if (fixture.exercise_content !== undefined) {
					expect(normalizeHtml(rendered.exercise_content)).toBe(normalizeHtml(fixture.exercise_content));
				}
			});
		});
	}
});
